function b = fir_bp(Fc1,Fc2,Fs,order)
%FIR_BP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 26-Sep-2017 23:58:57

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.

flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = blackmanharris(order+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(order, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);


% [EOF]
